/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { TempVm, TempVmInterface } from "../../VerifyAll.s.sol/TempVm";

const _abi = [
  {
    type: "function",
    name: "tryFfi",
    inputs: [
      {
        name: "",
        type: "string[]",
        internalType: "string[]",
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct FfiResult",
        components: [
          {
            name: "exit_code",
            type: "int32",
            internalType: "int32",
          },
          {
            name: "stdout",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "stderr",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
    ],
    stateMutability: "nonpayable",
  },
] as const;

export class TempVm__factory {
  static readonly abi = _abi;
  static createInterface(): TempVmInterface {
    return new utils.Interface(_abi) as TempVmInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): TempVm {
    return new Contract(address, _abi, signerOrProvider) as TempVm;
  }
}
