"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TempVm__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        type: "function",
        name: "tryFfi",
        inputs: [
            {
                name: "",
                type: "string[]",
                internalType: "string[]",
            },
        ],
        outputs: [
            {
                name: "",
                type: "tuple",
                internalType: "struct FfiResult",
                components: [
                    {
                        name: "exit_code",
                        type: "int32",
                        internalType: "int32",
                    },
                    {
                        name: "stdout",
                        type: "bytes",
                        internalType: "bytes",
                    },
                    {
                        name: "stderr",
                        type: "bytes",
                        internalType: "bytes",
                    },
                ],
            },
        ],
        stateMutability: "nonpayable",
    },
];
class TempVm__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.TempVm__factory = TempVm__factory;
TempVm__factory.abi = _abi;
