/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILayerZeroUserApplicationConfig,
  ILayerZeroUserApplicationConfigInterface,
} from "../ILayerZeroUserApplicationConfig";

const _abi = [
  {
    type: "function",
    name: "forceResumeReceive",
    inputs: [
      {
        name: "_srcChainId",
        type: "uint16",
        internalType: "uint16",
      },
      {
        name: "_srcAddress",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setConfig",
    inputs: [
      {
        name: "_version",
        type: "uint16",
        internalType: "uint16",
      },
      {
        name: "_chainId",
        type: "uint16",
        internalType: "uint16",
      },
      {
        name: "_configType",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_config",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setReceiveVersion",
    inputs: [
      {
        name: "_version",
        type: "uint16",
        internalType: "uint16",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSendVersion",
    inputs: [
      {
        name: "_version",
        type: "uint16",
        internalType: "uint16",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export class ILayerZeroUserApplicationConfig__factory {
  static readonly abi = _abi;
  static createInterface(): ILayerZeroUserApplicationConfigInterface {
    return new utils.Interface(
      _abi
    ) as ILayerZeroUserApplicationConfigInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILayerZeroUserApplicationConfig {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ILayerZeroUserApplicationConfig;
  }
}
