"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NonblockingLzApp__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        type: "function",
        name: "DEFAULT_PAYLOAD_SIZE_LIMIT",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "failedMessages",
        inputs: [
            {
                name: "",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "",
                type: "bytes",
                internalType: "bytes",
            },
            {
                name: "",
                type: "uint64",
                internalType: "uint64",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bytes32",
                internalType: "bytes32",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "forceResumeReceive",
        inputs: [
            {
                name: "_srcChainId",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "_srcAddress",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "getConfig",
        inputs: [
            {
                name: "_version",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "_chainId",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "",
                type: "address",
                internalType: "address",
            },
            {
                name: "_configType",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getTrustedRemoteAddress",
        inputs: [
            {
                name: "_remoteChainId",
                type: "uint16",
                internalType: "uint16",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "isTrustedRemote",
        inputs: [
            {
                name: "_srcChainId",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "_srcAddress",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "lzEndpoint",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "contract ILayerZeroEndpoint",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "lzReceive",
        inputs: [
            {
                name: "_srcChainId",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "_srcAddress",
                type: "bytes",
                internalType: "bytes",
            },
            {
                name: "_nonce",
                type: "uint64",
                internalType: "uint64",
            },
            {
                name: "_payload",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "minDstGasLookup",
        inputs: [
            {
                name: "",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "",
                type: "uint16",
                internalType: "uint16",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "nonblockingLzReceive",
        inputs: [
            {
                name: "_srcChainId",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "_srcAddress",
                type: "bytes",
                internalType: "bytes",
            },
            {
                name: "_nonce",
                type: "uint64",
                internalType: "uint64",
            },
            {
                name: "_payload",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "owner",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "payloadSizeLimitLookup",
        inputs: [
            {
                name: "",
                type: "uint16",
                internalType: "uint16",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "precrime",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "renounceOwnership",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "retryMessage",
        inputs: [
            {
                name: "_srcChainId",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "_srcAddress",
                type: "bytes",
                internalType: "bytes",
            },
            {
                name: "_nonce",
                type: "uint64",
                internalType: "uint64",
            },
            {
                name: "_payload",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "payable",
    },
    {
        type: "function",
        name: "setConfig",
        inputs: [
            {
                name: "_version",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "_chainId",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "_configType",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_config",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setMinDstGas",
        inputs: [
            {
                name: "_dstChainId",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "_packetType",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "_minGas",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setPayloadSizeLimit",
        inputs: [
            {
                name: "_dstChainId",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "_size",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setPrecrime",
        inputs: [
            {
                name: "_precrime",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setReceiveVersion",
        inputs: [
            {
                name: "_version",
                type: "uint16",
                internalType: "uint16",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setSendVersion",
        inputs: [
            {
                name: "_version",
                type: "uint16",
                internalType: "uint16",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setTrustedRemote",
        inputs: [
            {
                name: "_remoteChainId",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "_path",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setTrustedRemoteAddress",
        inputs: [
            {
                name: "_remoteChainId",
                type: "uint16",
                internalType: "uint16",
            },
            {
                name: "_remoteAddress",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "transferOwnership",
        inputs: [
            {
                name: "newOwner",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "trustedRemoteLookup",
        inputs: [
            {
                name: "",
                type: "uint16",
                internalType: "uint16",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "event",
        name: "MessageFailed",
        inputs: [
            {
                name: "_srcChainId",
                type: "uint16",
                indexed: false,
                internalType: "uint16",
            },
            {
                name: "_srcAddress",
                type: "bytes",
                indexed: false,
                internalType: "bytes",
            },
            {
                name: "_nonce",
                type: "uint64",
                indexed: false,
                internalType: "uint64",
            },
            {
                name: "_payload",
                type: "bytes",
                indexed: false,
                internalType: "bytes",
            },
            {
                name: "_reason",
                type: "bytes",
                indexed: false,
                internalType: "bytes",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            {
                name: "previousOwner",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "newOwner",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RetryMessageSuccess",
        inputs: [
            {
                name: "_srcChainId",
                type: "uint16",
                indexed: false,
                internalType: "uint16",
            },
            {
                name: "_srcAddress",
                type: "bytes",
                indexed: false,
                internalType: "bytes",
            },
            {
                name: "_nonce",
                type: "uint64",
                indexed: false,
                internalType: "uint64",
            },
            {
                name: "_payloadHash",
                type: "bytes32",
                indexed: false,
                internalType: "bytes32",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "SetMinDstGas",
        inputs: [
            {
                name: "_dstChainId",
                type: "uint16",
                indexed: false,
                internalType: "uint16",
            },
            {
                name: "_type",
                type: "uint16",
                indexed: false,
                internalType: "uint16",
            },
            {
                name: "_minDstGas",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "SetPrecrime",
        inputs: [
            {
                name: "precrime",
                type: "address",
                indexed: false,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "SetTrustedRemote",
        inputs: [
            {
                name: "_remoteChainId",
                type: "uint16",
                indexed: false,
                internalType: "uint16",
            },
            {
                name: "_path",
                type: "bytes",
                indexed: false,
                internalType: "bytes",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "SetTrustedRemoteAddress",
        inputs: [
            {
                name: "_remoteChainId",
                type: "uint16",
                indexed: false,
                internalType: "uint16",
            },
            {
                name: "_remoteAddress",
                type: "bytes",
                indexed: false,
                internalType: "bytes",
            },
        ],
        anonymous: false,
    },
    {
        type: "error",
        name: "OwnableInvalidOwner",
        inputs: [
            {
                name: "owner",
                type: "address",
                internalType: "address",
            },
        ],
    },
    {
        type: "error",
        name: "OwnableUnauthorizedAccount",
        inputs: [
            {
                name: "account",
                type: "address",
                internalType: "address",
            },
        ],
    },
];
class NonblockingLzApp__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.NonblockingLzApp__factory = NonblockingLzApp__factory;
NonblockingLzApp__factory.abi = _abi;
