version: '3.8'

services:
  avnil:
    container_name: avnil
    image: avnil
    build: 
      context: .
      dockerfile: Dockerfile-anvil
    ports:
      - 8545:8545
    

  app:
    container_name: app
    image: nestjs-app
    build: 
      context: .
      dockerfile: Dockerfile-api
    ports:
      - 3001:3001
    environment:
      APP_PORT: 3001
      APP_VERSION: 0.0.1

      # NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SDK_NEXT_PUBLIC_SUPABASE_URL }}
      # NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SDK_NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      # SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SDK_SUPABASE_SERVICE_ROLE_KEY }}
      # SUPABASE_JWT_SECRET: ${{ secrets.SDK_SUPABASE_JWT_SECRET }}
      # ETHERS_CUSTODIAN_PRIVATE_KEY: ${{ secrets.SDK_ETHERS_CUSTODIAN_PRIVATE_KEY }}
      # ETHERS_DEPLOYER_PRIVATE_KEY: ${{ secrets.SDK_ETHERS_DEPLOYER_PRIVATE_KEY }}
      # CRON_SECRET: ${{ secrets.SDK_CRON_SECRET }}
      # NEXT_PUBLIC_TARGET_NETWORK_WSS: ${{ secrets.SDK_NEXT_PUBLIC_TARGET_NETWORK_WSS }}
      # ETHERS_PROVIDER_URLS: ${{ secrets.SDK_ETHERS_PROVIDER_URLS }}

    depends_on:
      - supabase

  supabase:
    container_name: supabase
    image: public.ecr.aws/supabase/postgres:15.1.1.9
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  
  # supabase-kong:
  #   container_name: supabase-kong
  #   image: public.ecr.aws/supabase/kong:2.8.1
  #   ports:
  #     - 54321:8000
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres

# docker build -f Dockerfile -t imagename ../..
