##
# The Application Configuration for the DEV Environment (GitHub Actions).
# TODO: deprecated, remove. same as testnet config.
##

[evm]
# blockchain id, e.g. baseSepolia=84532, arbSepolia=421614
chain_id = 84532

[evm.address]
# credbull-devops wallets.  wallet numbers are 1-based (as opposed to 0-based in anvil)
# devops admin/owner (wallet 1)
owner = "0xD79Be36f61fce3B8EF2FBF22b13B2b9a68eE15A2"
# devops operator (wallet 2)
operator = "0xaD3C004eE1f942BFDA2DA0D2DAaC94d6aC012F75"

[evm.contracts.upside_vault]
# 2 decimal place percentage (meaining value divided by 100) as integer.
collateral_percentage = 200

[evm.contracts.token.cbl]
# CBL token params
max_supply = 10_000_000 # 10 million in wei

[services.supabase]
url = "https://kyvvhlnmoqibdihqrlmc.supabase.co"

# Export contract details to supabase.
export_contracts = true
