##
# The Application Configuration for the Local Environment (local development).
##

[services.supabase]
url = "http://127.0.0.1:54321"

[deployment]
# After contract deployment, update the `contract_addresses` table, or not.
update_contract_addresses = true

[deployment.vaults.address]
# Dev/Anvil Wallet, Account[0]
owner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
# Dev/Anvil Wallet, Account[1]
operator = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
# Dev/Anvil Wallet, Account[2]
custodian = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"

[deployment.vaults_support]
# Whether to deploy the Vaults Support contracts or not.
deploy = true

[deployment.cbl]
max_supply = 1_000_000_000 # 1 Billion in wei

[deployment.cbl.address]
# Dev/Anvil Wallet, Account[0]
owner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
# Dev/Anvil Wallet, Account[1]
minter = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
