##
# The Application Configuration for the Local Environment (local development).
##

[deployment.support]
deploy = true

[deployment.vaults.address]
# Dev/Anvil Wallet, Account[0]
owner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
# Dev/Anvil Wallet, Account[1]
operator = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
# Dev/Anvil Wallet, Account[2]
custodian = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"

[deployment.token.cbl]
max_supply = 10_000_000 # 10 million in wei

[deployment.token.cbl.address]
# Dev/Anvil Wallet, Account[0]
owner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
# Dev/Anvil Wallet, Account[1]
minter = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"

# =============================================================================

[services.supabase]
url = "http://127.0.0.1:54321"
update_contract_addresses = true
