##
# The Deployment Configuration for the MainNet Environment.
##

[services.supabase]
url = "https://kyvvhlnmoqibdihqrlmc.supabase.co"

[deployment]
# After contract deployment, update the `contract_addresses` table, or not.
update_contract_addresses = true

[deployment.vaults.address]
owner = "0xD79Be36f61fce3B8EF2FBF22b13B2b9a68eE15A2"
operator = "0xaD3C004eE1f942BFDA2DA0D2DAaC94d6aC012F75"
custodian = "0x8561845F6a9511cD8e2daCae77A961e718A77cF6"

[deployment.vaults_support]
# Whether to deploy the Vaults Support contracts or not.
deploy = false

[deployment.cbl]
max_supply = 1_000_000_000 # 1 Billion in wei

[deployment.cbl.address]
owner = "0xD79Be36f61fce3B8EF2FBF22b13B2b9a68eE15A2"
minter = "0xaD3C004eE1f942BFDA2DA0D2DAaC94d6aC012F75"
