##
# The Application Configuration for the Plume Mainnet Environment.
##

[evm]
# blockchain id, e.g. plumeMainnet=98865, plumeTestnet=98864, plumeTestnet_old=161221135, plumeDevnet=18230
chain_id = 98865
deploy_mocks = false


[evm.address]
# plume safe admin/owner https://safe.onchainden.com/home?safe=plume:0x79F6c1d2909726fA888f2104F6ba2047F683B436
owner = "0x79F6c1d2909726fA888f2104F6ba2047F683B436"
# plume safe oper/asset-mgr https://safe.onchainden.com/home?safe=plume:0x0C645bcdf7D842195576B8ebC289f661655D4A33
operator = "0x0C645bcdf7D842195576B8ebC289f661655D4A33"
# plume safe upgrader (none assigned)
upgrader = ""
# plume safe oper/asset-mgr https://safe.onchainden.com/home?safe=plume:0x0C645bcdf7D842195576B8ebC289f661655D4A33
asset_manager = "0x0C645bcdf7D842195576B8ebC289f661655D4A33"

# USDC.e token address - Bridged USDC (Stargate) (USDC.e)
usdc_token="0x3938A812c54304fEffD266C7E2E70B48F9475aD6"
# Liquid Continuous Multi Token Vault Proxy - Plume Mainnet
liquid_vault_proxy="0x2b9d2023DbF3c7473f1cec42F78713d09DdC9FBF"
# Liquid Continuous Multi Token Vault Impl - Plume Mainnet (v2 - latest)
liquid_vault_impl="0xD9991FC39980E4294F6953AB5aDf514Db8545658"
# Liquid Continuous Multi Token Vault Impl - Plume Mainnet (v1)
liquid_vault_impl_V1="0xe4a4d891f02DF7bFFc5ff9e691313DE8a9E76b91"


[evm.contracts.liquid_continuous_multi_token_vault]
# rate in basis points, e.g.  10% = 1000 bps
full_rate_bps = 10_00
# rate in basis points, e.g.  5.5% = 550 bps
reduced_rate_bps = 5_50
# December 4, 2024 2:00:00 PM UTC = 1733277600
vault_start_timestamp = 1733277600

[services.supabase]
url = ""

# Save the contract deployment details to the database.
update_contract_addresses = false