##
# The Application Configuration for the TestNet Environment.
##

[evm]
# blockchain id, e.g. baseSepolia=84532, arbSepolia=421614
chain_id = 84532

<<<<<<< HEAD
[evm.contracts]
# credbull-devops wallets.  wallet numbers are 1-based (as opposed to 0-based in anvil)
# devops admin/owner (wallet 1) - public address, okay to share
owner.public_address = "0xD79Be36f61fce3B8EF2FBF22b13B2b9a68eE15A2"
# devops operator (wallet 2) - public address, okay to share
operator.public_address = "0xaD3C004eE1f942BFDA2DA0D2DAaC94d6aC012F75"
=======
[evm.address]
# credbull-devops wallets.  wallet numbers are 1-based (as opposed to 0-based in anvil)
# devops admin/owner (wallet 1) - public address, okay to share
owner = "0xD79Be36f61fce3B8EF2FBF22b13B2b9a68eE15A2"
# devops operator (wallet 2) - public address, okay to share
operator = "0xaD3C004eE1f942BFDA2DA0D2DAaC94d6aC012F75"
<<<<<<< HEAD
>>>>>>> 4c8ceee7c87082b354260a8e51d03ed6212c3b40
=======
# devops custodian (wallet 3) - public address, okay to share
custodian = "0x8561845F6a9511cD8e2daCae77A961e718A77cF6"
>>>>>>> f764e2a0b3ca8c59b72c78f2cd6089f0542d4b61

[evm.contracts.upside_vault]
# 2 decimal place percentage (meaining value divided by 100) as integer.
collateral_percentage = 200

[services.supabase]
<<<<<<< HEAD

url = "https://kyvvhlnmoqibdihqrlmc.supabase.co"

# Export contract details to supabase.
export_contracts = true
=======
url = "https://kyvvhlnmoqibdihqrlmc.supabase.co"

# Export contract details to supabase.
export_contracts = true
>>>>>>> 4c8ceee7c87082b354260a8e51d03ed6212c3b40
