##
# The Application Configuration for the TestNet Environment.
##

[evm]
# blockchain id, e.g. baseSepolia=84532, arbSepolia=421614
chain_id = 421614
deploy_mocks = true

[evm.address]
# credbull-devops wallets.  wallet numbers are 1-based (as opposed to 0-based in anvil)
# devops admin/owner (wallet 1) - public address, okay to share
owner = "0xD79Be36f61fce3B8EF2FBF22b13B2b9a68eE15A2"
# devops operator (wallet 2) - public address, okay to share
operator = "0xaD3C004eE1f942BFDA2DA0D2DAaC94d6aC012F75"
# devops custodian (wallet 3) - public address, okay to share
custodian = "0x8561845F6a9511cD8e2daCae77A961e718A77cF6"

[evm.contracts.upside_vault]
# 2 decimal place percentage (meaining value divided by 100) as integer.
collateral_percentage = 200

[evm.contracts.cbl]
# CBL token params
# primevault Wallet "TEST - Testnet Owner Role v1.0"
owner = "0xd0065B8662846EaDB3F619c2e2b5b20Bdf47da36"
# primevault Wallet "TEST - Testnet Operator Role v1.0"
minter = "0x5103697D83F52D6184B55506345e4B7bbB300E2f"
# CBL token params
max_supply = 1_000_000_000 # 1 billion in wei

[services.supabase]
url = "https://kyvvhlnmoqibdihqrlmc.supabase.co"

# Save the contract deployment details to the database.
update_contract_addresses = true
