"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CredbullVaultFactoryTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CredbullVaultFactoryTest__factory_1 = require("./CredbullVaultFactoryTest__factory");
Object.defineProperty(exports, "CredbullVaultFactoryTest__factory", { enumerable: true, get: function () { return CredbullVaultFactoryTest__factory_1.CredbullVaultFactoryTest__factory; } });
