node_env = "development"

[api]
url = "https://credbull-defi-api-ci.fly.dev"

[app]
url = "http://127.0.0.1:3000"

[services.supabase]
url = "https://iucsqvvjujqcncowypnr.supabase.co"

[services.ethers]
# settings for baseSepolia, see others: https://chainlist.org/
url = "https://sepolia.base.org"
wss = "https://sepolia.base.org"

[evm.address]
# credbull-devops wallets.  wallet numbers are 1-based (as opposed to 0-based in anvil)
# devops admin/owner (wallet 1) - public address, okay to share
owner = "0xD79Be36f61fce3B8EF2FBF22b13B2b9a68eE15A2"
# devops operator (wallet 2) - public address, okay to share
operator = "0xaD3C004eE1f942BFDA2DA0D2DAaC94d6aC012F75"

# Dev/Anvil Wallet, Account[2]
custodian = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
# Dev/Anvil Wallet, Account[3]
treasury = "0x90F79bf6EB2c4f870365E785982E1f101E93b906"
# Dev/Anvil Wallet, Account[4]
activity_reward = "0xcabE80b332Aa9d900f5e32DF51cb0Bc5b276c556"

[users]
# Associated with Dev/Anvil Wallet, Account[0]
admin.email_address = "test+admin@credbull.io"
# Associated with Dev/Anvil Wallet, Account[7]
alice.email_address = "test+alice@credbull.io"
# Associated with Dev/Anvil Wallet, Account[8]
bob.email_address = "test+bob@credbull.io"

[operation.createVault]
collateral_percentage = 300
