node_env = "development"

[api]
url = "https://credbull-defi-api-ci.fly.dev"

[app]
url = "http://127.0.0.1:3000"

[services.supabase]
url = "https://iucsqvvjujqcncowypnr.supabase.co"

[services.ethers]
# settings for baseSepolia, see others: https://chainlist.org/
url = "https://sepolia.base.org"
wss = "https://sepolia.base.org"

[evm.address]
# credbull-devops wallets.  wallet numbers are 1-based (as opposed to 0-based in anvil)
# devops admin/owner (wallet 1) - public address, okay to share
owner = "0xD79Be36f61fce3B8EF2FBF22b13B2b9a68eE15A2"
# devops operator (wallet 2) - public address, okay to share
operator = "0xaD3C004eE1f942BFDA2DA0D2DAaC94d6aC012F75"

# devops custodian (wallet 3) - public address, okay to share
custodian = "0x8561845F6a9511cD8e2daCae77A961e718A77cF6"
# devops operator (wallet 4) - public address, okay to share
treasury = "0x77f07B5d5E03e39Dc42FBCa53F122D4c1851B939"
# devops operator (wallet 5) - public address, okay to share
activity_reward = "0x0822a51f5f8DB0480A0eA294099D56EA1aCcdC5c"

[users]
# Associated with devops admin/owner (wallet 1)
admin.email_address = "test+admin@credbull.io"
# Associated with devops alice (wallet 6)
alice.email_address = "test+alice@credbull.io"
# Associated with devops bob (wallet 7)
bob.email_address = "test+bob@credbull.io"

[operation.createVault]
collateral_percentage = 300
