"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CredbullVaultTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CredbullVaultTest__factory_1 = require("./CredbullVaultTest__factory");
Object.defineProperty(exports, "CredbullVaultTest__factory", { enumerable: true, get: function () { return CredbullVaultTest__factory_1.CredbullVaultTest__factory; } });
