revoke delete on table "public"."user_wallet" from "anon";

revoke insert on table "public"."user_wallet" from "anon";

revoke references on table "public"."user_wallet" from "anon";

revoke select on table "public"."user_wallet" from "anon";

revoke trigger on table "public"."user_wallet" from "anon";

revoke truncate on table "public"."user_wallet" from "anon";

revoke update on table "public"."user_wallet" from "anon";

revoke delete on table "public"."user_wallet" from "authenticated";

revoke insert on table "public"."user_wallet" from "authenticated";

revoke references on table "public"."user_wallet" from "authenticated";

revoke select on table "public"."user_wallet" from "authenticated";

revoke trigger on table "public"."user_wallet" from "authenticated";

revoke truncate on table "public"."user_wallet" from "authenticated";

revoke update on table "public"."user_wallet" from "authenticated";

revoke delete on table "public"."user_wallet" from "service_role";

revoke insert on table "public"."user_wallet" from "service_role";

revoke references on table "public"."user_wallet" from "service_role";

revoke select on table "public"."user_wallet" from "service_role";

revoke trigger on table "public"."user_wallet" from "service_role";

revoke truncate on table "public"."user_wallet" from "service_role";

revoke update on table "public"."user_wallet" from "service_role";

alter table "public"."user_wallet" drop constraint "user_wallet_user_id_fkey";

alter table "public"."user_wallet" drop constraint "user_wallets_pkey";

drop index if exists "public"."user_wallets_pkey";

drop table "public"."user_wallet";

create table "public"."user_wallets" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "address" text not null
);


alter table "public"."user_wallets" enable row level security;

CREATE UNIQUE INDEX user_wallets_pkey ON public.user_wallets USING btree (id);

alter table "public"."user_wallets" add constraint "user_wallets_pkey" PRIMARY KEY using index "user_wallets_pkey";

alter table "public"."user_wallets" add constraint "user_wallets_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_wallets" validate constraint "user_wallets_user_id_fkey";

grant delete on table "public"."user_wallets" to "anon";

grant insert on table "public"."user_wallets" to "anon";

grant references on table "public"."user_wallets" to "anon";

grant select on table "public"."user_wallets" to "anon";

grant trigger on table "public"."user_wallets" to "anon";

grant truncate on table "public"."user_wallets" to "anon";

grant update on table "public"."user_wallets" to "anon";

grant delete on table "public"."user_wallets" to "authenticated";

grant insert on table "public"."user_wallets" to "authenticated";

grant references on table "public"."user_wallets" to "authenticated";

grant select on table "public"."user_wallets" to "authenticated";

grant trigger on table "public"."user_wallets" to "authenticated";

grant truncate on table "public"."user_wallets" to "authenticated";

grant update on table "public"."user_wallets" to "authenticated";

grant delete on table "public"."user_wallets" to "service_role";

grant insert on table "public"."user_wallets" to "service_role";

grant references on table "public"."user_wallets" to "service_role";

grant select on table "public"."user_wallets" to "service_role";

grant trigger on table "public"."user_wallets" to "service_role";

grant truncate on table "public"."user_wallets" to "service_role";

grant update on table "public"."user_wallets" to "service_role";


