"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CredbullBaseVaultMock__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CredbullBaseVaultMock__factory_1 = require("./CredbullBaseVaultMock__factory");
Object.defineProperty(exports, "CredbullBaseVaultMock__factory", { enumerable: true, get: function () { return CredbullBaseVaultMock__factory_1.CredbullBaseVaultMock__factory; } });
