create type "public"."vault_distribution_entity_types" as enum ('activity_reward', 'treasury', 'vault', 'custodian');

alter table "public"."vaults" alter column "status" drop default;

alter type "public"."vault_status" rename to "vault_status__old_version_to_be_dropped";

create type "public"."vault_status" as enum ('created', 'ready', 'matured');

create table "public"."vault_distribution_configs" (
    "id" bigint generated by default as identity not null,
    "vault_id" bigint,
    "entity_id" bigint,
    "order" bigint not null,
    "percentage" double precision not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."vault_distribution_configs" enable row level security;

create table "public"."vault_distribution_entities" (
    "id" bigint generated by default as identity not null,
    "type" vault_distribution_entity_types not null,
    "address" text not null,
    "vault_id" bigint not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."vault_distribution_entities" enable row level security;

alter table "public"."vaults" alter column status type "public"."vault_status" using status::text::"public"."vault_status";

alter table "public"."vaults" alter column "status" set default 'created'::vault_status;

drop type "public"."vault_status__old_version_to_be_dropped";

CREATE UNIQUE INDEX vault_distribution_configs_pkey ON public.vault_distribution_configs USING btree (id);

CREATE UNIQUE INDEX vault_distribution_entities_pkey ON public.vault_distribution_entities USING btree (id);

alter table "public"."vault_distribution_configs" add constraint "vault_distribution_configs_pkey" PRIMARY KEY using index "vault_distribution_configs_pkey";

alter table "public"."vault_distribution_entities" add constraint "vault_distribution_entities_pkey" PRIMARY KEY using index "vault_distribution_entities_pkey";

alter table "public"."vault_distribution_configs" add constraint "vault_distribution_configs_entity_id_fkey" FOREIGN KEY (entity_id) REFERENCES vault_distribution_entities(id) ON DELETE CASCADE not valid;

alter table "public"."vault_distribution_configs" validate constraint "vault_distribution_configs_entity_id_fkey";

alter table "public"."vault_distribution_configs" add constraint "vault_distribution_configs_vault_id_fkey" FOREIGN KEY (vault_id) REFERENCES vaults(id) ON DELETE CASCADE not valid;

alter table "public"."vault_distribution_configs" validate constraint "vault_distribution_configs_vault_id_fkey";

alter table "public"."vault_distribution_entities" add constraint "vault_distribution_entities_vault_id_fkey" FOREIGN KEY (vault_id) REFERENCES vaults(id) ON DELETE CASCADE not valid;

alter table "public"."vault_distribution_entities" validate constraint "vault_distribution_entities_vault_id_fkey";

grant delete on table "public"."vault_distribution_configs" to "anon";

grant insert on table "public"."vault_distribution_configs" to "anon";

grant references on table "public"."vault_distribution_configs" to "anon";

grant select on table "public"."vault_distribution_configs" to "anon";

grant trigger on table "public"."vault_distribution_configs" to "anon";

grant truncate on table "public"."vault_distribution_configs" to "anon";

grant update on table "public"."vault_distribution_configs" to "anon";

grant delete on table "public"."vault_distribution_configs" to "authenticated";

grant insert on table "public"."vault_distribution_configs" to "authenticated";

grant references on table "public"."vault_distribution_configs" to "authenticated";

grant select on table "public"."vault_distribution_configs" to "authenticated";

grant trigger on table "public"."vault_distribution_configs" to "authenticated";

grant truncate on table "public"."vault_distribution_configs" to "authenticated";

grant update on table "public"."vault_distribution_configs" to "authenticated";

grant delete on table "public"."vault_distribution_configs" to "service_role";

grant insert on table "public"."vault_distribution_configs" to "service_role";

grant references on table "public"."vault_distribution_configs" to "service_role";

grant select on table "public"."vault_distribution_configs" to "service_role";

grant trigger on table "public"."vault_distribution_configs" to "service_role";

grant truncate on table "public"."vault_distribution_configs" to "service_role";

grant update on table "public"."vault_distribution_configs" to "service_role";

grant delete on table "public"."vault_distribution_entities" to "anon";

grant insert on table "public"."vault_distribution_entities" to "anon";

grant references on table "public"."vault_distribution_entities" to "anon";

grant select on table "public"."vault_distribution_entities" to "anon";

grant trigger on table "public"."vault_distribution_entities" to "anon";

grant truncate on table "public"."vault_distribution_entities" to "anon";

grant update on table "public"."vault_distribution_entities" to "anon";

grant delete on table "public"."vault_distribution_entities" to "authenticated";

grant insert on table "public"."vault_distribution_entities" to "authenticated";

grant references on table "public"."vault_distribution_entities" to "authenticated";

grant select on table "public"."vault_distribution_entities" to "authenticated";

grant trigger on table "public"."vault_distribution_entities" to "authenticated";

grant truncate on table "public"."vault_distribution_entities" to "authenticated";

grant update on table "public"."vault_distribution_entities" to "authenticated";

grant delete on table "public"."vault_distribution_entities" to "service_role";

grant insert on table "public"."vault_distribution_entities" to "service_role";

grant references on table "public"."vault_distribution_entities" to "service_role";

grant select on table "public"."vault_distribution_entities" to "service_role";

grant trigger on table "public"."vault_distribution_entities" to "service_role";

grant truncate on table "public"."vault_distribution_entities" to "service_role";

grant update on table "public"."vault_distribution_entities" to "service_role";

create policy "Enable select for authenticated users only"
on "public"."vault_distribution_configs"
as permissive
for select
to authenticated
using (true);


create policy "Enable select for authenticated users only"
on "public"."vault_distribution_entities"
as permissive
for select
to authenticated
using (true);



