/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { AKYCProvider, AKYCProviderInterface } from "../AKYCProvider";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "status",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_addresses",
        type: "address[]",
      },
      {
        internalType: "bool[]",
        name: "_statuses",
        type: "bool[]",
      },
    ],
    name: "updateStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class AKYCProvider__factory {
  static readonly abi = _abi;
  static createInterface(): AKYCProviderInterface {
    return new utils.Interface(_abi) as AKYCProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AKYCProvider {
    return new Contract(address, _abi, signerOrProvider) as AKYCProvider;
  }
}
