[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
solc_version="0.8.23"
optimizer = true
optimizer_runs = 200

[fmt]
bracket_spacing = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"
base = "https://mainnet.base.org"
baseSepolia = "https://sepolia.base.org"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrumSepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimismSepolia = "https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonAmoy = "https://polygon-amoy.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
bitlayer = "https://rpc.bitlayer.org"
bitlayerTestnet = "https://testnet-rpc.bitlayer.org"
plume = "https://rpc.plume.org"
plumeTestnet = "https://testnet-rpc.plume.org"
# deprecated chains
plume_98865 = "https://rpc.plumenetwork.xyz/${PLUME_API_KEY}"
plumeTestnet_98864= "https://test-rpc.plumenetwork.xyz"
plumeTestnet_18230 = "https://devnet-rpc.plumenetwork.xyz"
plumeTestnet_161221135 = "https://testnet-rpc.plume.org"


[etherscan]
localhost = { key = "" , url="http://127.0.0.1:8545"}
base = { key = "${ETHERSCAN_API_KEY}" }
baseSepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.arbiscan.io/api", chain=42161 }
arbitrumSepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api", chain=421614 }
bitlayer = { key = "bitlayer", url="https://rpc.bitlayer.org" }
bitlayerTestnet = { key = "bitlayerTestnet", url="https://testnet-scan.bitlayer.org" }
plume = { key = "plume", url = 'https://explorer.plume.org/api\?', chain=98866 }
plumeTestnet = { key = "plumeTestnet", url = 'https://testnet-explorer.plume.org/api\?', chain=98867 }
polygon = { key = "${ETHERSCAN_API_KEY}" }
polygonAmoy = { key = "${ETHERSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api", chain=80002 }
# deprecated chains
plume_98865 = { key = "plume_98865", url = 'https://explorer.plumenetwork.xyz/api\?', chain=98865 }
plumeTestnet_98864 = { key = "plumeTestnet_98864", url = 'https://test-explorer.plumenetwork.xyz/api\?', chain=98864 }
plumeTestnet_18230 = { key = "plumeTestnet_18230", url = 'https://devnet-explorer.plumenetwork.xyz/api\?', chain=18230 }
plumeTestnet_161221135 = { key = "plumeTestnet_161221135", url = 'https://testnet-explorer.plume.org/api\?', chain=161221135 }
