"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MockERC721__factory = exports.IERC721TokenReceiver__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IERC721TokenReceiver__factory_1 = require("./IERC721TokenReceiver__factory");
Object.defineProperty(exports, "IERC721TokenReceiver__factory", { enumerable: true, get: function () { return IERC721TokenReceiver__factory_1.IERC721TokenReceiver__factory; } });
var MockERC721__factory_1 = require("./MockERC721__factory");
Object.defineProperty(exports, "MockERC721__factory", { enumerable: true, get: function () { return MockERC721__factory_1.MockERC721__factory; } });
