// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title IBuyableAsyncSellable
 * @dev Interface for buying and selling tokens.  Selling requires a two-step request and sell process.
 */
interface IBuyableAsyncSellable {
    /// @notice Buy a specified `amount` of tokens.
    function buy(uint256 amount) external returns (uint256 shares);

    /// @notice Request to sell a specified `amount` of tokens.
    function sellRequest(uint256 amount) external;

    /// @notice Fulfill a sell request for the specified `amount` of tokens.
    function fulfillSellRequest(uint256 amount) external;

    /// @notice Returns the total yield generated by the contract.
    function yieldGenerated() external view returns (uint256 yield);
}
