/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface DeployVaultInterface extends utils.Interface {
  functions: {
    "IS_SCRIPT()": FunctionFragment;
    "deployFixedYieldVault(address,uint256,uint256,uint256)": FunctionFragment;
    "run()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "IS_SCRIPT" | "deployFixedYieldVault" | "run"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "IS_SCRIPT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deployFixedYieldVault",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "run", values?: undefined): string;

  decodeFunctionResult(functionFragment: "IS_SCRIPT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployFixedYieldVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "run", data: BytesLike): Result;

  events: {};
}

export interface DeployVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DeployVaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<[boolean]>;

    deployFixedYieldVault(
      helperConfig: string,
      promisedYield: BigNumberish,
      opensAt: BigNumberish,
      closesDuration: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    run(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  IS_SCRIPT(overrides?: CallOverrides): Promise<boolean>;

  deployFixedYieldVault(
    helperConfig: string,
    promisedYield: BigNumberish,
    opensAt: BigNumberish,
    closesDuration: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  run(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  callStatic: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<boolean>;

    deployFixedYieldVault(
      helperConfig: string,
      promisedYield: BigNumberish,
      opensAt: BigNumberish,
      closesDuration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    run(overrides?: CallOverrides): Promise<[string[], string]>;
  };

  filters: {};

  estimateGas: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<BigNumber>;

    deployFixedYieldVault(
      helperConfig: string,
      promisedYield: BigNumberish,
      opensAt: BigNumberish,
      closesDuration: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    run(overrides?: Overrides & { from?: string }): Promise<BigNumber>;
  };

  populateTransaction: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deployFixedYieldVault(
      helperConfig: string,
      promisedYield: BigNumberish,
      opensAt: BigNumberish,
      closesDuration: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    run(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
