"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeployLZMoneyTransfer__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var DeployLZMoneyTransfer__factory_1 = require("./DeployLZMoneyTransfer__factory");
Object.defineProperty(exports, "DeployLZMoneyTransfer__factory", { enumerable: true, get: function () { return DeployLZMoneyTransfer__factory_1.DeployLZMoneyTransfer__factory; } });
