##
# The Application Configuration for the TestNet Environment.
##

node_env = "testnet"

[api]
#TODO - confirm port
port = 3001
version = "0.0.1"

[services.sync_vaults]
block_history = 1000

[services.supabase]
url = "https://kyvvhlnmoqibdihqrlmc.supabase.co"

[services.ethers]
# settings for baseSepolia, see others: https://chainlist.org/
url = "https://sepolia.base.org"
wss = "https://sepolia.base.org"

[evm.address]
# devops operator (wallet 2) - public address, okay to share
operator = "0xaD3C004eE1f942BFDA2DA0D2DAaC94d6aC012F75"
