"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.WindowPlugInTest__factory = exports.WindowPlugIn__factory = exports.WhitelistVaultMock__factory = exports.WhitelistPlugInTest__factory = exports.WhitelistPlugIn__factory = exports.VmSafe__factory = exports.Vm__factory = exports.StdStorageSafe__factory = exports.StdInvariant__factory = exports.StdError__factory = exports.StdAssertions__factory = exports.Script__factory = exports.SafeERC20__factory = exports.Ownable__factory = exports.MockToken__factory = exports.MockStablecoin__factory = exports.MockKYCProvider__factory = exports.MockERC721__factory = exports.IERC721TokenReceiver__factory = exports.MockERC20__factory = exports.MaturityVaultTest__factory = exports.MaturityVaultMock__factory = exports.MaturityVault__factory = exports.Math__factory = exports.IMulticall3__factory = exports.IERC4626__factory = exports.IERC20Permit__factory = exports.IERC20Metadata__factory = exports.IERC20__factory = exports.IERC165__factory = exports.IAccessControl__factory = exports.HelperConfig__factory = exports.FixedYieldVault__factory = exports.ERC4626__factory = exports.ERC20__factory = exports.ERC165__factory = exports.DeployVaultFactory__factory = exports.CredbullVaultFactoryTest__factory = exports.CredbullVaultFactory__factory = exports.CredbullUpsideVaultFactory__factory = exports.CredbullUpsideVault__factory = exports.CredbullFixedYieldVaultTest__factory = exports.CredbullFixedYieldVault__factory = exports.CredbullBaseVaultTest__factory = exports.CredbullBaseVaultMock__factory = exports.CredbullBaseVault__factory = exports.Address__factory = exports.AccessControl__factory = exports.AKYCProvider__factory = exports.factories = void 0;
exports.Test__factory = exports.DSTest__factory = exports.IERC721Errors__factory = exports.IERC20Errors__factory = exports.IERC1155Errors__factory = exports.WindowVaultMock__factory = void 0;
exports.factories = __importStar(require("./factories"));
var AKYCProvider__factory_1 = require("./factories/AKYCProvider__factory");
Object.defineProperty(exports, "AKYCProvider__factory", { enumerable: true, get: function () { return AKYCProvider__factory_1.AKYCProvider__factory; } });
var AccessControl__factory_1 = require("./factories/AccessControl__factory");
Object.defineProperty(exports, "AccessControl__factory", { enumerable: true, get: function () { return AccessControl__factory_1.AccessControl__factory; } });
var Address__factory_1 = require("./factories/Address__factory");
Object.defineProperty(exports, "Address__factory", { enumerable: true, get: function () { return Address__factory_1.Address__factory; } });
var CredbullBaseVault__factory_1 = require("./factories/CredbullBaseVault__factory");
Object.defineProperty(exports, "CredbullBaseVault__factory", { enumerable: true, get: function () { return CredbullBaseVault__factory_1.CredbullBaseVault__factory; } });
var CredbullBaseVaultMock__factory_1 = require("./factories/CredbullBaseVaultMock.m.sol/CredbullBaseVaultMock__factory");
Object.defineProperty(exports, "CredbullBaseVaultMock__factory", { enumerable: true, get: function () { return CredbullBaseVaultMock__factory_1.CredbullBaseVaultMock__factory; } });
var CredbullBaseVaultTest__factory_1 = require("./factories/CredbullBaseVaultTest.t.sol/CredbullBaseVaultTest__factory");
Object.defineProperty(exports, "CredbullBaseVaultTest__factory", { enumerable: true, get: function () { return CredbullBaseVaultTest__factory_1.CredbullBaseVaultTest__factory; } });
var CredbullFixedYieldVault__factory_1 = require("./factories/CredbullFixedYieldVault__factory");
Object.defineProperty(exports, "CredbullFixedYieldVault__factory", { enumerable: true, get: function () { return CredbullFixedYieldVault__factory_1.CredbullFixedYieldVault__factory; } });
var CredbullFixedYieldVaultTest__factory_1 = require("./factories/CredbullFixedYieldVaultTest.t.sol/CredbullFixedYieldVaultTest__factory");
Object.defineProperty(exports, "CredbullFixedYieldVaultTest__factory", { enumerable: true, get: function () { return CredbullFixedYieldVaultTest__factory_1.CredbullFixedYieldVaultTest__factory; } });
var CredbullUpsideVault__factory_1 = require("./factories/CredbullUpsideVault__factory");
Object.defineProperty(exports, "CredbullUpsideVault__factory", { enumerable: true, get: function () { return CredbullUpsideVault__factory_1.CredbullUpsideVault__factory; } });
var CredbullUpsideVaultFactory__factory_1 = require("./factories/CredbullUpsideVaultFactory__factory");
Object.defineProperty(exports, "CredbullUpsideVaultFactory__factory", { enumerable: true, get: function () { return CredbullUpsideVaultFactory__factory_1.CredbullUpsideVaultFactory__factory; } });
var CredbullVaultFactory__factory_1 = require("./factories/CredbullVaultFactory__factory");
Object.defineProperty(exports, "CredbullVaultFactory__factory", { enumerable: true, get: function () { return CredbullVaultFactory__factory_1.CredbullVaultFactory__factory; } });
var CredbullVaultFactoryTest__factory_1 = require("./factories/CredbullVaultFactory.t.sol/CredbullVaultFactoryTest__factory");
Object.defineProperty(exports, "CredbullVaultFactoryTest__factory", { enumerable: true, get: function () { return CredbullVaultFactoryTest__factory_1.CredbullVaultFactoryTest__factory; } });
var DeployVaultFactory__factory_1 = require("./factories/DeployVaultFactory.s.sol/DeployVaultFactory__factory");
Object.defineProperty(exports, "DeployVaultFactory__factory", { enumerable: true, get: function () { return DeployVaultFactory__factory_1.DeployVaultFactory__factory; } });
var ERC165__factory_1 = require("./factories/ERC165__factory");
Object.defineProperty(exports, "ERC165__factory", { enumerable: true, get: function () { return ERC165__factory_1.ERC165__factory; } });
var ERC20__factory_1 = require("./factories/ERC20__factory");
Object.defineProperty(exports, "ERC20__factory", { enumerable: true, get: function () { return ERC20__factory_1.ERC20__factory; } });
var ERC4626__factory_1 = require("./factories/ERC4626__factory");
Object.defineProperty(exports, "ERC4626__factory", { enumerable: true, get: function () { return ERC4626__factory_1.ERC4626__factory; } });
var FixedYieldVault__factory_1 = require("./factories/FixedYieldVault__factory");
Object.defineProperty(exports, "FixedYieldVault__factory", { enumerable: true, get: function () { return FixedYieldVault__factory_1.FixedYieldVault__factory; } });
var HelperConfig__factory_1 = require("./factories/HelperConfig.s.sol/HelperConfig__factory");
Object.defineProperty(exports, "HelperConfig__factory", { enumerable: true, get: function () { return HelperConfig__factory_1.HelperConfig__factory; } });
var IAccessControl__factory_1 = require("./factories/IAccessControl__factory");
Object.defineProperty(exports, "IAccessControl__factory", { enumerable: true, get: function () { return IAccessControl__factory_1.IAccessControl__factory; } });
var IERC165__factory_1 = require("./factories/IERC165__factory");
Object.defineProperty(exports, "IERC165__factory", { enumerable: true, get: function () { return IERC165__factory_1.IERC165__factory; } });
var IERC20__factory_1 = require("./factories/IERC20__factory");
Object.defineProperty(exports, "IERC20__factory", { enumerable: true, get: function () { return IERC20__factory_1.IERC20__factory; } });
var IERC20Metadata__factory_1 = require("./factories/IERC20Metadata__factory");
Object.defineProperty(exports, "IERC20Metadata__factory", { enumerable: true, get: function () { return IERC20Metadata__factory_1.IERC20Metadata__factory; } });
var IERC20Permit__factory_1 = require("./factories/IERC20Permit__factory");
Object.defineProperty(exports, "IERC20Permit__factory", { enumerable: true, get: function () { return IERC20Permit__factory_1.IERC20Permit__factory; } });
var IERC4626__factory_1 = require("./factories/IERC4626__factory");
Object.defineProperty(exports, "IERC4626__factory", { enumerable: true, get: function () { return IERC4626__factory_1.IERC4626__factory; } });
var IMulticall3__factory_1 = require("./factories/IMulticall3__factory");
Object.defineProperty(exports, "IMulticall3__factory", { enumerable: true, get: function () { return IMulticall3__factory_1.IMulticall3__factory; } });
var Math__factory_1 = require("./factories/Math__factory");
Object.defineProperty(exports, "Math__factory", { enumerable: true, get: function () { return Math__factory_1.Math__factory; } });
var MaturityVault__factory_1 = require("./factories/MaturityVault__factory");
Object.defineProperty(exports, "MaturityVault__factory", { enumerable: true, get: function () { return MaturityVault__factory_1.MaturityVault__factory; } });
var MaturityVaultMock__factory_1 = require("./factories/MaturityVaultMock.m.sol/MaturityVaultMock__factory");
Object.defineProperty(exports, "MaturityVaultMock__factory", { enumerable: true, get: function () { return MaturityVaultMock__factory_1.MaturityVaultMock__factory; } });
var MaturityVaultTest__factory_1 = require("./factories/MaturityVaultTest.t.sol/MaturityVaultTest__factory");
Object.defineProperty(exports, "MaturityVaultTest__factory", { enumerable: true, get: function () { return MaturityVaultTest__factory_1.MaturityVaultTest__factory; } });
var MockERC20__factory_1 = require("./factories/MockERC20__factory");
Object.defineProperty(exports, "MockERC20__factory", { enumerable: true, get: function () { return MockERC20__factory_1.MockERC20__factory; } });
var IERC721TokenReceiver__factory_1 = require("./factories/MockERC721.sol/IERC721TokenReceiver__factory");
Object.defineProperty(exports, "IERC721TokenReceiver__factory", { enumerable: true, get: function () { return IERC721TokenReceiver__factory_1.IERC721TokenReceiver__factory; } });
var MockERC721__factory_1 = require("./factories/MockERC721.sol/MockERC721__factory");
Object.defineProperty(exports, "MockERC721__factory", { enumerable: true, get: function () { return MockERC721__factory_1.MockERC721__factory; } });
var MockKYCProvider__factory_1 = require("./factories/MockKYCProvider__factory");
Object.defineProperty(exports, "MockKYCProvider__factory", { enumerable: true, get: function () { return MockKYCProvider__factory_1.MockKYCProvider__factory; } });
var MockStablecoin__factory_1 = require("./factories/MockStablecoin__factory");
Object.defineProperty(exports, "MockStablecoin__factory", { enumerable: true, get: function () { return MockStablecoin__factory_1.MockStablecoin__factory; } });
var MockToken__factory_1 = require("./factories/MockToken__factory");
Object.defineProperty(exports, "MockToken__factory", { enumerable: true, get: function () { return MockToken__factory_1.MockToken__factory; } });
var Ownable__factory_1 = require("./factories/Ownable__factory");
Object.defineProperty(exports, "Ownable__factory", { enumerable: true, get: function () { return Ownable__factory_1.Ownable__factory; } });
var SafeERC20__factory_1 = require("./factories/SafeERC20__factory");
Object.defineProperty(exports, "SafeERC20__factory", { enumerable: true, get: function () { return SafeERC20__factory_1.SafeERC20__factory; } });
var Script__factory_1 = require("./factories/Script__factory");
Object.defineProperty(exports, "Script__factory", { enumerable: true, get: function () { return Script__factory_1.Script__factory; } });
var StdAssertions__factory_1 = require("./factories/StdAssertions__factory");
Object.defineProperty(exports, "StdAssertions__factory", { enumerable: true, get: function () { return StdAssertions__factory_1.StdAssertions__factory; } });
var StdError__factory_1 = require("./factories/StdError.sol/StdError__factory");
Object.defineProperty(exports, "StdError__factory", { enumerable: true, get: function () { return StdError__factory_1.StdError__factory; } });
var StdInvariant__factory_1 = require("./factories/StdInvariant__factory");
Object.defineProperty(exports, "StdInvariant__factory", { enumerable: true, get: function () { return StdInvariant__factory_1.StdInvariant__factory; } });
var StdStorageSafe__factory_1 = require("./factories/StdStorage.sol/StdStorageSafe__factory");
Object.defineProperty(exports, "StdStorageSafe__factory", { enumerable: true, get: function () { return StdStorageSafe__factory_1.StdStorageSafe__factory; } });
var Vm__factory_1 = require("./factories/Vm.sol/Vm__factory");
Object.defineProperty(exports, "Vm__factory", { enumerable: true, get: function () { return Vm__factory_1.Vm__factory; } });
var VmSafe__factory_1 = require("./factories/Vm.sol/VmSafe__factory");
Object.defineProperty(exports, "VmSafe__factory", { enumerable: true, get: function () { return VmSafe__factory_1.VmSafe__factory; } });
var WhitelistPlugIn__factory_1 = require("./factories/WhitelistPlugIn__factory");
Object.defineProperty(exports, "WhitelistPlugIn__factory", { enumerable: true, get: function () { return WhitelistPlugIn__factory_1.WhitelistPlugIn__factory; } });
var WhitelistPlugInTest__factory_1 = require("./factories/WhitelistPlugInTest.t.sol/WhitelistPlugInTest__factory");
Object.defineProperty(exports, "WhitelistPlugInTest__factory", { enumerable: true, get: function () { return WhitelistPlugInTest__factory_1.WhitelistPlugInTest__factory; } });
var WhitelistVaultMock__factory_1 = require("./factories/WhitelistVaultMock.m.sol/WhitelistVaultMock__factory");
Object.defineProperty(exports, "WhitelistVaultMock__factory", { enumerable: true, get: function () { return WhitelistVaultMock__factory_1.WhitelistVaultMock__factory; } });
var WindowPlugIn__factory_1 = require("./factories/WindowPlugIn__factory");
Object.defineProperty(exports, "WindowPlugIn__factory", { enumerable: true, get: function () { return WindowPlugIn__factory_1.WindowPlugIn__factory; } });
var WindowPlugInTest__factory_1 = require("./factories/WindowPlugInTest.t.sol/WindowPlugInTest__factory");
Object.defineProperty(exports, "WindowPlugInTest__factory", { enumerable: true, get: function () { return WindowPlugInTest__factory_1.WindowPlugInTest__factory; } });
var WindowVaultMock__factory_1 = require("./factories/WindowVaultMock.m.sol/WindowVaultMock__factory");
Object.defineProperty(exports, "WindowVaultMock__factory", { enumerable: true, get: function () { return WindowVaultMock__factory_1.WindowVaultMock__factory; } });
var IERC1155Errors__factory_1 = require("./factories/draft-IERC6093.sol/IERC1155Errors__factory");
Object.defineProperty(exports, "IERC1155Errors__factory", { enumerable: true, get: function () { return IERC1155Errors__factory_1.IERC1155Errors__factory; } });
var IERC20Errors__factory_1 = require("./factories/draft-IERC6093.sol/IERC20Errors__factory");
Object.defineProperty(exports, "IERC20Errors__factory", { enumerable: true, get: function () { return IERC20Errors__factory_1.IERC20Errors__factory; } });
var IERC721Errors__factory_1 = require("./factories/draft-IERC6093.sol/IERC721Errors__factory");
Object.defineProperty(exports, "IERC721Errors__factory", { enumerable: true, get: function () { return IERC721Errors__factory_1.IERC721Errors__factory; } });
var DSTest__factory_1 = require("./factories/test.sol/DSTest__factory");
Object.defineProperty(exports, "DSTest__factory", { enumerable: true, get: function () { return DSTest__factory_1.DSTest__factory; } });
var Test__factory_1 = require("./factories/test.sol/Test__factory");
Object.defineProperty(exports, "Test__factory", { enumerable: true, get: function () { return Test__factory_1.Test__factory; } });
