##
# The Application Configuration for the TestNet Environment.
##

[evm]
# blockchain id, e.g. baseSepolia=84532, arbSepolia=421614, sepolia=11155111, optimismSepolia=11155420
chain_id = 11155420
deploy_mocks = true


[services.supabase]
url = "https://kyvvhlnmoqibdihqrlmc.supabase.co"

# Save the contract deployment details to the database.
update_contract_addresses = true
