name: ci-api

defaults:
  run:
    working-directory: packages/api

on:
  workflow_dispatch:
  push:
    branches: [ "main*" ]
    paths:
      - "packages/api/**"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn run test
