name: ci-app

defaults:
  run:
    working-directory: packages/app

on:
  workflow_dispatch:
  push:
    branches: [ "main*" ]
    paths:
      - "packages/app/**"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn run test
        env:
          # the environment variables below should be removed when we configure the secrets in github
          NEXT_PUBLIC_SUPABASE_URL: your_supabase_project_url
          NEXT_PUBLIC_SUPABASE_ANON_KEY: your_supabase_anon_key
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: your_wallet_connect_project_id
          SUPABASE_SERVICE_ROLE_KEY: your_supabase_service_role_key
          API_BASE_URL: http://localhost:3001
          APP_BASE_URL: http://localhost:3000
