name: ci-dev-contracts

defaults:
  run:
    working-directory: packages/contracts

on:
  workflow_dispatch:
  push:
    branches:
      - "main*"
      - "development*"
    paths:
      - "packages/contracts/**"

jobs:
  check-env:
    runs-on: ubuntu-latest
    environment: testnet

    steps:
      - uses: actions/checkout@v3

      - name: Hello world!
        run: echo "hello world!"

      - name: Credbull environment
        run: |
          echo "Github job is: $GITHUB_JOB"
          echo "Environment is: $ENVIRONMENT"
          echo "A secret is: $SOME_SECRET"
        env:
          # in github, these will come fromthe environment
          # locally, load using ```act --var-file my.variables``` (see https://nektosact.com/usage/index.html)
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
          
