name: ci-dev-sdk

defaults:
  run:
    working-directory: .

on:
  push:
    branches: [ "*" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: yarn install

      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: docker-compose.yml
          compose-command: up
          compose-options: --build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SDK_NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SDK_NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SDK_SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_JWT_SECRET: ${{ secrets.SDK_SUPABASE_JWT_SECRET }}
          ETHERS_CUSTODIAN_PRIVATE_KEY: ${{ secrets.SDK_ETHERS_CUSTODIAN_PRIVATE_KEY }}
          ETHERS_DEPLOYER_PRIVATE_KEY: ${{ secrets.SDK_ETHERS_DEPLOYER_PRIVATE_KEY }}
          CRON_SECRET: ${{ secrets.SDK_CRON_SECRET }}
          NEXT_PUBLIC_TARGET_NETWORK_WSS: ${{ secrets.SDK_NEXT_PUBLIC_TARGET_NETWORK_WSS }}
          ETHERS_PROVIDER_URLS: ${{ secrets.SDK_ETHERS_PROVIDER_URLS }}
          APP_PORT: 3001
          APP_VERSION: 0.0.1

      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: cd packages/api/supabase && supabase link --project-ref ${{ secrets.SDK_SUPABASE_PROJECT_ID }} && supabase db push
        env: 
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SDK_SUPABASE_ACCESS_TOKEN }}
          PROJECT_ID: ${{ secrets.SDK_SUPABASE_PROJECT_ID }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SDK_SUPABASE_DB_PASSWORD }}

      - name: Check network
        run: docker network ls

      - name: Check containers
        run: docker ps
      
      - name: Deploy contracts
        run: cd packages/contracts/ && yarn deploy
        env:
          EXPORT_TO_SUPABASE: true
          NEXT_PUBLIC_TARGET_NETWORK_ID: 31337
          COLLATERAL_PERCENTAGE: 200
          DEFAULT_ANVIL_KEY: ${{ secrets.SDK_DEFAULT_ANVIL_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          VAULT_OPENS_AT_TIMESTAMP: ${{ secrets.SDK_VAULT_OPENS_AT_TIMESTAMP }}
          VAULT_CLOSES_DURATION_TIMESTAMP: ${{ secrets.SDK_VAULT_CLOSES_DURATION_TIMESTAMP }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SDK_NEXT_PUBLIC_SUPABASE_URL }}
          PUBLIC_OPERATOR_ADDRESS: ${{ secrets.SDK_PUBLIC_OPERATOR_ADDRESS }}
          PUBLIC_OWNER_ADDRESS: ${{ secrets.SDK_PUBLIC_OWNER_ADDRESS }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SDK_SUPABASE_SERVICE_ROLE_KEY }}
      
      # - name: Create default users
      #   run: cd scripts/operation/ && yarn op --create-default-users
      
      - name: Create FixedYieldVault
        run: cd scripts/operation/ && yarn op --create-vault
        env:
          API_BASE_URL: ${{ secrets.SDK_API_BASE_URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SDK_NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SDK_NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_TARGET_NETWORK: ${{ secrets.SDK_NEXT_PUBLIC_TARGET_NETWORK }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SDK_SUPABASE_SERVICE_ROLE_KEY }}
          ADMIN_PRIVATE_KEY: ${{ secrets.SDK_ADMIN_PRIVATE_KEY }}
          ADMIN_EMAIL: ${{ secrets.SDK_ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.SDK_ADMIN_PASSWORD }}

      - name: Create UpsideVault
        run: cd scripts/operation/ && yarn op --create-vault upside upsideVault:self

      - name: Run SDK tests
        run: cd packages/sdk/ && yarn test