name: ci-dev-api

defaults:
  run:
    working-directory: packages/api

on:
  workflow_dispatch:
  push:
    branches: [ "main*" ]
    paths:
      - "packages/api/**"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn run test
        env:
          # the environment variables below should be removed when we configure the secrets in github
          APP_PORT: 3001
          APP_VERSION: 0.0.1
          NEXT_PUBLIC_SUPABASE_URL: your_supabase_url
          NEXT_PUBLIC_SUPABASE_ANON_KEY: your_supabase_anon_key
          SUPABASE_SERVICE_ROLE_KEY: your_supabase_service_role_key
          SUPABASE_JWT_SECRET: your_supabase_jwt_secret
          ETHERS_DEPLOYER_PRIVATE_KEY: your_deployer_private_key
          ETHERS_INFURA_API_KEY: your_infura_api_key
          CRON_SECRET: any_string_will_do
          NEXT_PUBLIC_TARGET_NETWORK_WSS: ws://localhost:8545

  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    needs: test
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy ../.. --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
