name: ci-dev-ops

defaults:
  run:
    working-directory: .

on:
  workflow_dispatch:
  push:
    branches:
      - "main*"
      - "development*"
      - "fix-github-actions"
    paths:
      - "packages/ops/**"
      - "packages/contracts/**"
      - "packages/api/**"
      - ".github/workflows/ci-dev-ops.yml"

jobs:
  ops-int-test-setup:
    uses: ./.github/workflows/ci-local-setup.yml

  ops-int-test:
    runs-on: ubuntu-latest
    environment: local
    needs: [ops-int-test-setup]
    steps:
      - name: Run Ops Integration Tests
        run: yarn int-test
        working-directory: packages/ops

      - name: See API Logs, If Tests Failed
        run: docker logs api
        if: ${{ failure() }}

  ops-int-test-teardown:
    uses: ./.github/workflows/ci-local-teardown.yml
    needs: [ops-int-test]
