name: ci-dev-app
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

defaults:
  run:
    working-directory: packages/app

on:
  workflow_dispatch:
    branches:
      - "main*"
      - "development*"
      - "ops*"
    paths:
      - "packages/app/**"
      - "packages/contracts/**"
      - ".github/workflows/ci-dev-app.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn run test
        env:
          # the environment variables below should be removed when we configure the secrets in github
          NEXT_PUBLIC_SUPABASE_URL: your_supabase_project_url
          NEXT_PUBLIC_SUPABASE_ANON_KEY: your_supabase_anon_key
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: your_wallet_connect_project_id
          SUPABASE_SERVICE_ROLE_KEY: your_supabase_service_role_key
          API_BASE_URL: http://localhost:3001
          APP_BASE_URL: http://localhost:3000

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --cwd ../.. --token=${{ secrets.VERCEL_TOKEN }}
#
      - name: Build Project Artifacts
        run: vercel build --cwd ../.. --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --cwd ../.. --token=${{ secrets.VERCEL_TOKEN }}
