name: ci-dev-api

defaults:
  run:
    working-directory: packages/api

on:
  workflow_dispatch:
  push:
    branches:
      - "main*"
      - "development*"
    paths:
      - "packages/api/**"
      - "packages/contracts/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: testnet

    steps:
      - uses: actions/checkout@v4

      - name: Install yarn
        run: npm install -g yarn

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn run test
        env:
          # Dev/Anvil Wallet, PrivateKey[1] - okay to share
          OPERATOR_PRIVATE_KEY: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
          SUPABASE_JWT_SECRET: anything-testing-only
          CRON_SECRET : anything-testing-only
          SLACK_TOKEN: anything-testing-only

      - name: Build API
        run: yarn build && yarn run sentry:sourcemaps
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Deploying to fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy ../.. --remote-only -t ${{ secrets.FLY_DEPLOY_TOKEN }}

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_ORG: credbull
          SENTRY_PROJECT: credbull-defi-api
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Install yarn
        run: npm install -g yarn