name: ci-dev-ops

defaults:
  run:
    working-directory: .

on:
  workflow_dispatch:
  push:
    branches:
      - "main*"
      - "development*"
    paths:
      - "packages/ops/**"
      - "packages/contracts/**"
      - "packages/api/**"
      - ".github/workflows/ci-dev-ops.yml"

jobs:
  ops-int-test:
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yarn
        run: |
          corepack prepare yarn@stable --activate
          npm install -g yarn

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.2.0
        with:
          version: nightly

      - name: Install Project Dependencies
        run: yarn install

      - name: Run Ops tests
        run: yarn int-test
        working-directory: packages/ops
        env:
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEVOPS_SEPOLIA_DEPLOYER_PRIVATE_KEY }}
          ADMIN_PRIVATE_KEY: ${{ secrets.DEVOPS_SEPOLIA_ADMIN_PRIVATE_KEY }}
          ALICE_PRIVATE_KEY: ${{ secrets.DEVOPS_SEPOLIA_ALICE_PRIVATE_KEY }}
          BOB_PRIVATE_KEY: ${{ secrets.DEVOPS_SEPOLIA_BOB_PRIVATE_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          ADMIN_PASSWORD: NeverGuessThis
          ALICE_PASSWORD: alice-1234
          BOB_PASSWORD: bobword

