name: ci-as-if-local-teardown

defaults:
  run:
    working-directory: .

on:
  workflow_call:

jobs:
  teardown-ci-as-if-local:
    runs-on: ubuntu-latest
    environment: local
    steps:
      - name: Shutdown Docker Compose Services
        run: docker compose --env-file packages/api/.env down
        if: ${{ always() }}

      - name: Stop Supabase
        run: supabase stop --no-backup
        working-directory: packages/api
        if: ${{ always() }}
