name: ci-as-if-local-setup

defaults:
  run:
    working-directory: .

on:
  workflow_call:

jobs:
  setup-ci-as-if-local:
    runs-on: ubuntu-latest
    environment: local
    steps:
      - name: Checkout credbull-defi
        uses: actions/checkout@v4

      - name: Install yarn
        run: |
          corepack prepare yarn@stable --activate
          npm install -g yarn

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.2.0
        with:
          version: nightly

      - name: Install Project Dependencies
        run: yarn install

      - name: Setup Local Environment
        run: find . -type f -name ".env*.sample" -exec sh -c 'F={}; cp -nv $F $(dirname $F)/$(basename $F .sample)' \;

      - name: Build Project
        run: yarn build

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1.3.0
        with:
          version: latest

      - name: Start Supabase
        run: supabase start
        working-directory: packages/api

      - name: Run Docker Compose with Background Services
        run: docker compose --env-file packages/api/.env up --detach --build --wait

      - name: Deploy Credbull Contracts
        run: yarn deploy
        working-directory: packages/contracts

      - name: Create Default Users
        run: yarn op --create-default-users
        working-directory: packages/ops
