on: [push]

name: Run tests

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        working-directory: ./packages/foundry
        run: forge test -vvv

      - name: Run coverage report
        working-directory: ./packages/foundry
        run: forge coverage
