"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WhitelistPlugTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var WhitelistPlugTest__factory_1 = require("./WhitelistPlugTest__factory");
Object.defineProperty(exports, "WhitelistPlugTest__factory", { enumerable: true, get: function () { return WhitelistPlugTest__factory_1.WhitelistPlugTest__factory; } });
